# Generated by Django 3.0.6 on 2020-05-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('expense', models.IntegerField()),
                ('category', models.CharField(max_length=150)),
                ('dot', models.DateTimeField()),
            ],
        ),
    ]
