# Generated by Django 3.0.6 on 2020-05-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='budget',
            field=models.IntegerField(default=0),
        ),
    ]
