# Generated by Django 3.0.6 on 2020-06-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0008_auto_20200601_0029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.AddField(
            model_name='expense',
            name='budget',
            field=models.IntegerField(default=0),
        ),
    ]
