# Generated by Django 3.0.6 on 2020-06-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0011_auto_20200603_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='budget',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
