# Generated by Django 3.0.6 on 2020-06-03 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0013_auto_20200603_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='budget',
        ),
    ]
