# Generated by Django 3.0.6 on 2020-06-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0016_auto_20200604_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='transactions',
            field=models.IntegerField(default=0),
        ),
    ]
