# Generated by Django 3.0.6 on 2020-06-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0017_expense_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='transactions',
            field=models.IntegerField(default=1),
        ),
    ]
