# Generated by Django 3.0.6 on 2020-06-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0018_auto_20200607_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='transactions',
            field=models.IntegerField(default=0),
        ),
    ]
