# Generated by Django 3.0.6 on 2020-06-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0020_auto_20200608_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='receipt',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
