# Generated by Django 3.0.6 on 2020-06-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0021_auto_20200608_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='budgetleft',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
