# Generated by Django 3.0.6 on 2020-06-08 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0022_budget_budgetleft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='budgetleft',
        ),
    ]
