# Generated by Django 3.0.6 on 2020-06-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0026_remove_expense_totalexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='budget',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
