# Generated by Django 3.0.6 on 2020-06-09 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0027_expense_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='budget',
        ),
    ]
