# Generated by Django 3.0.6 on 2020-06-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0028_remove_expense_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment',
            field=models.CharField(default='cash', max_length=100),
        ),
    ]
