# Generated by Django 3.0.6 on 2020-06-10 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0029_expense_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='userin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.Expense'),
        ),
    ]
