# Generated by Django 3.0.6 on 2020-06-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0031_auto_20200611_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='source',
            field=models.CharField(default='Salary Income', max_length=50),
        ),
    ]
