# Generated by Django 3.0.6 on 2020-06-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0032_budget_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='receipt',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
