# Generated by Django 3.0.8 on 2020-07-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0033_auto_20200613_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='receipt',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
