# Generated by Django 3.0.8 on 2020-07-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0034_auto_20200728_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='receipt',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
