# Generated by Django 3.0.8 on 2020-07-28 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0035_auto_20200728_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='transactions',
        ),
    ]
